global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'run-service'
    static_configs:
      - targets: ['run-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'tracking-service'
    static_configs:
      - targets: ['tracking-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'document-service'
    static_configs:
      - targets: ['document-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 