version: '3.8'

services:
  run-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://user:password@postgres:5432/send_runs?schema=public
      - JWT_SECRET=your-secret-key
      - RABBITMQ_URL=amqp://rabbitmq
      - RABBITMQ_EXCHANGE=run_events
      - RABBITMQ_QUEUE=run_notifications
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - send-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=send_runs
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - send-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - send-network

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  send-network:
    driver: bridge 